"""
Django settings for stdmark project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os

from pathlib import Path



# BASE DIRECTORY

BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY

SECRET_KEY = 'django-insecure-p5xhabij82xg(rg37sv@(+ndbdz#8p-pdo(5zi(!$)(=e%mn!a'

DEBUG = False



# ALLOWED HOSTS

ALLOWED_HOSTS = [

    "student-grade-calculator-yu9q.onrender.com",

    "student-grade-calculator-1-phzz.onrender.com",

    "127.0.0.1",

    "localhost",

]



# CORS SETTINGS

CORS_ALLOWED_ORIGINS = [
    "https://student-grade-calculator-yu9q.onrender.com",
    "https://student-grade-calculator-1-phzz.onrender.com",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]



CSRF_TRUSTED_ORIGINS = [

    "https://student-grade-calculator-yu9q.onrender.com",

    "https://student-grade-calculator-1-phzz.onrender.com",

]



# SESSION SETTINGS

SESSION_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_HTTPONLY = True



LOGIN_URL = "/login/"



# APPLICATIONS

INSTALLED_APPS = [

    "corsheaders",

    "django.contrib.admin",

    "django.contrib.auth",

    "django.contrib.contenttypes",

    "django.contrib.sessions",

    "django.contrib.messages",

    "django.contrib.staticfiles",

    "myapp",

]



# MIDDLEWARE

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]



# ROOT URL CONFIG

ROOT_URLCONF = "stdmark.urls"



# TEMPLATES

TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]



# WSGI

WSGI_APPLICATION = "stdmark.wsgi.application"



# DATABASE

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",

    }

}



# PASSWORD VALIDATION

AUTH_PASSWORD_VALIDATORS = [

    {

        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",

    },

    {

        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",

    },

    {

        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",

    },

    {

        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",

    },

]



# INTERNATIONALIZATION

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# STATIC FILES

STATIC_URL = "static/"



# EMAIL SETTINGS

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")

EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@student-grade-calculator.onrender.com"
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")


# DEFAULT AUTO FIELD

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"